box: generic/centos7
vm_name: sddoclrn
public_ip: 192.168.0.26
esxi_hostport: 22
esxi_disk_store: VMSTORE
guest_name: sddoclrn
guest_memsize: 4048
guest_numvcpus: 2
guest_guestos: 'centos-64'
esxi_virtual_network: VM_PUBLIC