box: generic/centos7
vm_name: gitlab
public_ip: 192.168.3.30
esxi_hostport: 22
esxi_disk_store: VMSTORE
guest_name: gitlab
guest_memsize: 2048
guest_numvcpus: 1
guest_guestos: 'centos-64'
esxi_virtual_network: VLAN20